# Generated by Django 5.1 on 2024-08-21 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Gear Categories',
            },
        ),
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('material_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='gear_images/')),
                ('highlight', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to='workout_gear.gearcategory')),
            ],
        ),
    ]
