# Generated by Django 5.1 on 2024-09-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_gear', '0002_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
