# Generated by Django 5.1 on 2024-11-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_gear', '0003_gearitem_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearitem',
            name='image_url',
        ),
    ]
